version: '3'

services:

  #tm_rabbitmq_server:
  #  image: ra/connectors/rabbitmq_server
  #  build: ./connectors/dashboard_connector/server-rabbitmq

  tm_dashboard_connector:
    image: ra/connectors/dashboard_connector
    build: ./connectors/dashboard_connector
    volumes:
      - './logs/tm_connectors/dashboard:/logs'
#    links:
#      - tm_rabbitmq_server:rabbitmq_server

  tm_dare_connector:
    image: ra/connectors/dare_connector
    build: ./connectors/dare_connector
    volumes:
      - './logs/tm_connectors/dare:/logs'

  tm_store_connector:
    image: ra/connectors/store_connector
    build: ./connectors/store_connector
    volumes:
      - './logs/tm_connectors/store:/logs'

  tm_database_redis:
    image: ra/connectors/redis
    build: ./connectors/database

  tm_vnsfo_connector:
    image: ra/connectors/tm_vnsfo_connector
    build: ./connectors/vnsfo_connector
    volumes:
      - './logs/tm_connectors/vnsfo:/logs'

  tm_vimemu_connector:
    image: ra/connectors/tm_vimemu_connector
    build: ./connectors/vimemu_connector
    volumes:
      - './logs/tm_connectors/vimemu:/logs'

  reverse_proxy:
    image: ra/trust_monitor/reverse_proxy
    build: ./reverseProxy
    depends_on:
      - tm_django_app
    links:
      - tm_django_app:tm_django_app
      - tm_static_serve:tm_static_serve
    volumes:
      - './reverseProxy/ssl:/etc/ssl:ro'
      - './logs/reverse_proxy:/var/log/nginx'
    ports:
      - 80:80
      - 443:443

  tm_django_app:
    image: ra/trust_monitor/tm_django_app
    build: ./trustMonitor
    environment:
      - RUN_DJANGO_APP=1
    depends_on:
      - tm_static_serve
    links:
      - tm_dare_connector:tm_dare_connector
      - tm_dashboard_connector:tm_dashboard_connector
      - tm_store_connector:tm_store_connector
      - tm_database_redis:tm_database_redis
      - tm_vnsfo_connector:tm_vnsfo_connector
      - tm_vimemu_connector:tm_vimemu_connector
    volumes:
      - './logs/tm_django_app:/logs'
      - './trustMonitor/docker/db:/db'
      # Integration with HPE switchVerifier
      - './hpe:/hpe'
  tm_static_serve:
    image: ra/trust_monitor_tm_static_serve
    build: ./trustMonitor
    environment:
      - SERVE_STATIC=1

  tm_scheduler:
    image: ra/trust_monitor_tm_scheduler
    build: ./scheduler
    depends_on:
      - tm_django_app:
    links:
      - tm_django_app:dm_django_app
    volumes:
      - './logs/tm_scheduler:/logs'
